apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-user
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
